version: '2'
services:
  web:
    build: .
    ports:
     - "5000:80"
    volumes:
     - .:/code
  database:
    image: "mysql"
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci]
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=phabricator